################################################################
# Global configuration
################################################################

defaultEntryPoints = ["http"]

[entryPoints]
    [entryPoints.http]
    address = ":80"

[retry]

[healthcheck]
interval = "15s"

################################################################
# Web configuration backend
################################################################

[web]
address = ":8080"

[web.metrics.prometheus]

################################################################
# Consul Catalog configuration backend
################################################################

[consulCatalog]
endpoint = "consul:8500"
domain = "uas.nt.public"
prefix = "traefik"
exposedByDefault = false
watch = true
