---
version: '3.4'

services:
  toolclinet:
    build: ./image/tool/cli/net
    image: tool-cli-net
    labels:
      SERVICE_IGNORE: 'true'

  toolclirabbitmq:
    image: rabbitmq:3.7-management
    labels:
      SERVICE_IGNORE: 'true'
    environment:
      RABBITMQ_ERLANG_COOKIE: ${PROJECT_NAME}

  dns:
    image: andyshinn/dnsmasq
    restart: unless-stopped
    command: -d
    labels:
      SERVICE_IGNORE: 'true'

networks:
  default:
...