---
version: '3.4'

services:
  toolclinet:
    build: ./image/tool/cli/net
    image: tool-cli-net
    labels:
      SERVICE_IGNORE: 'true'

  dns:
    image: andyshinn/dnsmasq
    restart: unless-stopped
    command: -d
    labels:
      SERVICE_IGNORE: 'true'

networks:
  default:
...